### ISSUE TITLE
Add ability to compare intervals

### ISSUE THREAD

**Issue by jamerlan** [AutohomeCorp/autohome-compareQueries-datasource#14]
Hi! Thank you for the plugin!

Is it possible to compare by selected interval?

For example if selected 12h then I can compare by (current-12) - (current-(12 * 2)) -  (current-(12 * 3))
If 5 days selected then: (current-5d) - (current-(5d * 2)) -  (current-(5d * 3))
and so on..

Also currently it's not clear for me.. how it works if I compare by 1 week, 2 weeks, but selected interval is 1 hour. For example, if it's Monday.. Will it compare with another Mondays the same hour?

Thanks a lot for your work!

**Comment by nfw999** [comment]
![image](https://user-images.githubusercontent.com/33611490/98186713-54761d80-1f4a-11eb-9b3c-e82d03a95f6a.png)


The first question, You can add a variable, but currently timeshift does not support operations, such as 2*$timshift, you can only use one variable to add one timeshift .

The second question, you are right, it will compare with another Mondays the same hour.
