### ISSUE TITLE
Plugin seems incompatible with grafana 8.3.0

### ISSUE THREAD

**Issue by Dalvany** [AutohomeCorp/autohome-compareQueries-datasource#24]
Hello, I just switch to grafana 8.3.0 and it seems they made some changes that render the plugin incompatible : I have an exception `Datasource [object Object] was not found`.
Panels that does not use compare queries seems to work.

**Comment by diakbar** [comment]
+1

**Comment by diakbar** [comment]
after googling it's because unsigned plugins, please signed this plugin

**Comment by diakbar** [comment]
![image](https://user-images.githubusercontent.com/1845987/144802494-5da19c84-5c07-488e-9861-58aeb051134a.png)

after allow unsigned, still get error 
CompareQueries: Datasource [object Object] was not found

grafana version : 8.3.0

**Comment by MiCRoPhoBIC** [comment]
We have the same issue with 8.3.1 here. 
8.2.7 works fine.

**Comment by Dalvany** [comment]
Trying to debug, it seems that at [this line](https://github.com/AutohomeCorp/autohome-compareQueries-datasource/blob/master/src/datasource.ts#L36) `dsName`parameter is the string `[object Object]`  
![image](https://user-images.githubusercontent.com/9901407/145476413-3ae61d05-905c-4ea5-ac57-89527ad441b7.png)

**Comment by diakbar** [comment]
great job @Dalvany , confirmed latest version is worked now.
![image](https://user-images.githubusercontent.com/1845987/145609297-4820f6c2-fc64-4714-b74c-f835dffd9de3.png)

**Comment by gesnus** [comment]
Hi,

I have applied the latest version of the pluggin in my grafana 8.3.2 and I keep getting the same error, what can I be doing wrong? I have downloaded the Source Code, I have unzipped it and I have replaced all the content in the directory / var / lib / grafana / plugins / autohome-compareQueries-datasource

![imagen](https://user-images.githubusercontent.com/44234557/147352465-2c29b323-6ae9-4b3b-8444-e2c5586616e8.png)

Thanks.

**Comment by nfw999** [comment]
I downloaded the Source code v1.0.1 and unzipped it  .  grafana 8.3.2 works fine. 
Confirm whether there are other plugin directories or the old plugin have not been replaced
