### ISSUE TITLE
grafana 7.5.6.  :    undefined: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by faryang-sh** [AutohomeCorp/autohome-compareQueries-datasource#25]
install grafana with docker, command is : 

docker run -d \
-p 3001:3000 \
--name=grafana-plugin \
-e "GF_INSTALL_PLUGINS=https://github.com/AutohomeCorp/autohome-compareQueries-datasource/releases/download/v1.0.0/autohome-comparequeries-datasource.zip;autohome-comparequeries-datasource" \
grafana/grafana:7.5.6

the error message is :      undefined: Cannot read properties of undefined (reading '0')

**Comment by nfw999** [comment]
Install grafana with docker using the same command and the plugin works fine. Please provide more context information

**Comment by zhangle910522** [comment]
<img width="656" alt="1655257082224" src="https://user-images.githubusercontent.com/28779854/173717814-b9f8fc34-bbf8-4690-ae10-00adcf38a78b.png">
我这也出现同样的问题了   CompareQueries: Cannot read properties of undefined (reading '0')

**Comment by nereus-east** [comment]
+1

**Comment by nereus-east** [comment]
@zhangle910522 https://github.com/AutohomeCorp/autohome-compareQueries-datasource/issues/37 FYI.
