### ISSUE TITLE
Datasource [object Object] was not found

### ISSUE THREAD

**Issue by gesnus** [AutohomeCorp/autohome-compareQueries-datasource#28]
I have updated my grafana to version 8.3.2 and the following error appeared in my dashboards with the CompareQueries plugin.
![imagen](https://user-images.githubusercontent.com/44234557/147103634-15c454c6-ca2e-4998-acc6-51ab1b469df7.png)
![imagen](https://user-images.githubusercontent.com/44234557/147103706-5552675d-9c7b-4d45-962b-a40729038c18.png)

I have applied the latest version of the plugin but I keep getting the same error. 
![GrafanaPluginCompareQueries](https://user-images.githubusercontent.com/44234557/147103191-88e73468-d880-4229-b44a-6218f2776add.jpg)

That could be happening? The Data Source test appears to be correct. 
![imagen](https://user-images.githubusercontent.com/44234557/147104022-13bca285-e840-4c3d-92bb-3aad04b79e6d.png)

**Comment by nfw999** [comment]
Issue [#28157](https://github.com/AutohomeCorp/autohome-compareQueries-datasource/issues/24) has a same exception message
