### ISSUE TITLE
创建datasource报错

### ISSUE THREAD

**Issue by uglyliu** [AutohomeCorp/autohome-compareQueries-datasource#29]
大佬，我创建datasource报下面的错，请问怎么处理哇

Plugin Error
Fetch error: 404 Not Found Instantiating https://XXXXXX/public/@grafana/data Loading https://XXXXX/public/plugins/autohome-comparequeries-datasource/module.js Loading plugins/autohome-comparequeries-datasource/module

Grafana版本：v5.2.1

**Comment by nfw999** [comment]
是下载的源码到插件目录么

**Comment by uglyliu** [comment]
> 是下载的源码到插件目录么

是的

**Comment by uglyliu** [comment]
> 是下载的源码到插件目录么

![image](https://user-images.githubusercontent.com/22983421/148002996-1b9ef373-7dae-4751-b589-d8b33c9f09a2.png)

**Comment by uglyliu** [comment]
> 是下载的源码到插件目录么

grafana后台也显示有这个插件了
![image](https://user-images.githubusercontent.com/22983421/148003339-3c448d77-a13c-4e5a-9785-fbd1d981f7cb.png)

**Comment by uglyliu** [comment]
> 是下载的源码到插件目录么
创建datasource报的错，v1.0.0和v1.0.1这2个版本都试过了，都会报下面的错误
![image](https://user-images.githubusercontent.com/22983421/148003468-6bd5c219-4abb-4fdb-8a2c-d0608c745476.png)

**Comment by nfw999** [comment]
![image](https://user-images.githubusercontent.com/33611490/148008057-ba844258-bdf2-4296-bcef-f894ae09a31d.png)

我试了下5.2.1，没有复现问题

1、你看下报了哪些js错误
2、试下其他开源数据源看下是不是有相同问题

**Comment by uglyliu** [comment]
> ![image](https://user-images.githubusercontent.com/33611490/148008057-ba844258-bdf2-4296-bcef-f894ae09a31d.png)
> 
> 我试了下5.2.1，没有复现问题
> 
> 1、你看下报了哪些js错误 2、试下其他开源数据源看下是不是有相同问题

js 报的错误，试了下其他的开源插件，没有报404，能否贴下grafana.ini配置文件？我发现我换了6.2.5版本也是报同样的问题，感觉是我的grafana配置有问题
![image](https://user-images.githubusercontent.com/22983421/148012360-3121947d-2bb5-4dd3-8a78-33503dea078c.png)

**Comment by nfw999** [comment]
没有特殊配置，主要修改了[paths][server][database][session]几个节点

```
##################### Grafana Configuration Example #####################
#
# Everything has defaults so you only need to uncomment things you want to
# change

# possible values : production, development
;app_mode = production

# instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
;instance_name = ${HOSTNAME}

#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
data = /data/grafana/5.2.1/data

# Directory where grafana can store logs
logs = /data/grafana/5.2.1/log

# Directory where grafana will automatically scan and look for plugins
plugins = /data/grafana/5.2.1/plugins

# folder that contains provisioning config files that grafana will apply on startup and while running.
;provisioning = conf/provisioning

#################################### Server ####################################
[server]
domain = autohome.com.cn
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
;domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = %(protocol)s://%(domain)s/

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =

#################################### Database ####################################
[database]
# You can configure the database connection by specifying type, host, name, user and password
# as separate properties or as on string using the url properties.

# Either "mysql", "postgres" or "sqlite3", it's your choice
type = mysql
host = xxx.autohome.com.cn:3307
name = xxx
user = xxx
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = """xxxxxx"""

# Use either URL or the previous fields to configure the database
# Example: mysql://user:secret@host:port/database
;url =

# For "postgres" only, either "disable", "require" or "verify-full"
;ssl_mode = disable

# For "sqlite3" only, path relative to data_path setting
;path = grafana.db

# Max idle conn setting default is 2
;max_idle_conn = 2

# Max conn setting default is 0 (mean not set)
;max_open_conn =

# Connection Max Lifetime default is 14400 (means 14400 seconds or 4 hours)
;conn_max_lifetime = 14400

# Set to true to log the sql calls and execution times.
log_queries =

#################################### Session ####################################
[session]
# Either "memory", "file", "redis", "mysql", "postgres", default is "file"
;provider = file

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
;provider_config = sessions

# Session cookie name
;cookie_name = grafana_sess

# If you use session in https only, default is false
;cookie_secure = false

# Session life time, default is 86400
;session_life_time = 86400

provider = mysql
provider_config = """xxx:xxx@tcp(xxxx.autohome.com.cn:3307)/xxxx"""
cookie_name = grafana_sess
cookie_secure = false
session_life_time = 2592000

#################################### Data proxy ###########################
[dataproxy]

# This enables data proxy logging, default is false
;logging = false

#################################### Analytics ####################################
[analytics]
# Server reporting, sends usage counters to stats.grafana.org every 24 hours.
# No ip addresses are being tracked, only simple counters to track
# running instances, dashboard and error counts. It is very helpful to us.
# Change this option to false to disable reporting.
;reporting_enabled = true

# Set to false to disable all checks to https://grafana.net
# for new vesions (grafana itself and plugins), check is used
# in some UI views to notify that grafana or plugin update exists
# This option does not cause any auto updates, nor send any information
# only a GET request to http://grafana.com to get latest versions
;check_for_updates = true

# Google Analytics universal tracking code, only enabled if you specify an id here
;google_analytics_ua_id =

#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

# used for signing
;secret_key = SW2YcwTIb9zpOOhoPsMm

# Auto-login remember days
;login_remember_days = 7
;cookie_username = grafana_user
;cookie_remember_name = grafana_remember

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
;data_source_proxy_whitelist =

# disable protection against brute force login attempts
;disable_brute_force_login_protection = false

#################################### Snapshots ###########################
[snapshots]
# snapshot sharing options
;external_enabled = true
;external_snapshot_url = https://snapshots-origin.raintank.io
;external_snapshot_name = Publish to snapshot.raintank.io

# remove expired snapshot
;snapshot_remove_expired = true

#################################### Dashboards History ##################
[dashboards]
# Number dashboard versions to keep (per dashboard). Default: 20, Minimum: 1
;versions_to_keep = 20

#################################### Users ###############################
[users]
# disable user signup / registration
allow_sign_up = true

# Allow non admin users to create organizations
allow_org_create = true

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Default role new users will be automatically assigned (if disabled above is set to true)
auto_assign_org_role = Viewer

# Background text for the user field on the login page
login_hint = email or username

# Default UI theme ("dark" or "light")
default_theme = dark

# External user management, these options affect the organization users view
;external_manage_link_url =
;external_manage_link_name =
;external_manage_info =

# Viewers can edit/inspect dashboard settings in the browser. But not save the dashboard.
;viewers_can_edit = false

[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
;disable_login_form = false

# Set to true to disable the signout link in the side menu. useful if you use auth.proxy, defaults to false
;disable_signout_menu = false

#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

#################################### Github Auth ##########################
[auth.github]
;enabled = false
;allow_sign_up = true
;client_id = some_id
;client_secret = some_secret
;scopes = user:email,read:org
;auth_url = https://github.com/login/oauth/authorize
;token_url = https://github.com/login/oauth/access_token
;api_url = https://api.github.com/user
;team_ids =
;allowed_organizations =

#################################### Google Auth ##########################
[auth.google]
;enabled = false
;allow_sign_up = true
;client_id = some_client_id
;client_secret = some_client_secret
;scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
;auth_url = https://accounts.google.com/o/oauth2/auth
;token_url = https://accounts.google.com/o/oauth2/token
;api_url = https://www.googleapis.com/oauth2/v1/userinfo
;allowed_domains =

#################################### Generic OAuth ##########################
[auth.generic_oauth]
;enabled = false
;name = OAuth
;allow_sign_up = true
;client_id = some_id
;client_secret = some_secret
;scopes = user:email,read:org
;auth_url = https://foo.bar/login/oauth/authorize
;token_url = https://foo.bar/login/oauth/access_token
;api_url = https://foo.bar/user
;team_ids =
;allowed_organizations =

#################################### Grafana.com Auth ####################
[auth.grafana_com]
;enabled = false
;allow_sign_up = true
;client_id = some_id
;client_secret = some_secret
;scopes = user:email
;allowed_organizations =

#################################### Auth Proxy ##########################
[auth.proxy]
;enabled = false
;header_name = X-WEBAUTH-USER
;header_property = username
;auto_sign_up = true
;ldap_sync_ttl = 60
;whitelist = 192.168.1.1, 192.168.2.1

#################################### Basic Auth ##########################
[auth.basic]
;enabled = true

#################################### Auth LDAP ##########################
[auth.ldap]
;enabled = false
;config_file = /etc/grafana/ldap.toml
;allow_sign_up = true

#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = xxxx
user =xxxx
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password =xxxx
;cert_file =
;key_file =
;skip_verify = false
from_address = xxxx
from_name = Grafana
# EHLO identity in SMTP dialog (defaults to instance_name)
;ehlo_identity = dashboard.example.com

[emails]
;welcome_email_on_sign_up = false

#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info

# optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
;filters =

# For "console" mode only
[log.console]
;level =

# log line format, valid options are text, console and json
;format = console

# For "file" mode only
[log.file]
;level =

# log line format, valid options are text, console and json
;format = text

# This enables automated log rotate(switch of following options), default is true
;log_rotate = true

# Max line number of single file, default is 1000000
;max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
;max_size_shift = 28

# Segment log daily, default is true
;daily_rotate = true

# Expired days of log file(delete after max days), default is 7
;max_days = 7

[log.syslog]
;level =

# log line format, valid options are text, console and json
;format = text

# Syslog network type and address. This can be udp, tcp, or unix. If left blank, the default unix endpoints will be used.
;network =
;address =

# Syslog facility. user, daemon and local0 through local7 are valid.
;facility =

# Syslog tag. By default, the process' argv[0] is used.
;tag =

#################################### Alerting ############################
[alerting]
# Disable alerting engine & UI features
;enabled = true
# Makes it possible to turn off alert rule execution but alerting UI is visible
;execute_alerts = true

#################################### Internal Grafana Metrics ##########################
# Metrics available at HTTP API Url /metrics
[metrics]
# Disable / Enable internal metrics
;enabled           = true

# Publish interval
;interval_seconds  = 10

# Send internal metrics to Graphite
[metrics.graphite]
# Enable by setting the address setting (ex localhost:2003)
;address =
;prefix = prod.grafana.%(instance_name)s.

#################################### Distributed tracing ############
[tracing.jaeger]
# Enable by setting the address sending traces to jaeger (ex localhost:6831)
;address = localhost:6831
# Tag that will always be included in when creating new spans. ex (tag1:value1,tag2:value2)
;always_included_tag = tag1:value1
# Type specifies the type of the sampler: const, probabilistic, rateLimiting, or remote
;sampler_type = const
# jaeger samplerconfig param
# for "const" sampler, 0 or 1 for always false/true respectively
# for "probabilistic" sampler, a probability between 0 and 1
# for "rateLimiting" sampler, the number of spans per second
# for "remote" sampler, param is the same as for "probabilistic"
# and indicates the initial sampling rate before the actual one
# is received from the mothership
;sampler_param = 1

#################################### Grafana.com integration  ##########################
# Url used to to import dashboards directly from Grafana.com
[grafana_com]
;url = https://grafana.com

#################################### External image storage ##########################
[external_image_storage]
# Used for uploading images to public servers so they can be included in slack/email messages.
# you can choose between (s3, webdav, gcs, azure_blob, local)
;provider =

[external_image_storage.s3]
;bucket =
;region =
;path =
;access_key =
;secret_key =

[external_image_storage.webdav]
;url =
;public_url =
;username =
;password =

[external_image_storage.gcs]
;key_file =
;bucket =
;path =

[external_image_storage.azure_blob]
;account_name =
;account_key =
;container_name =

[external_image_storage.local]
# does not require any configuration

```

**Comment by uglyliu** [comment]
> 没有特殊配置，主要修改了[paths][server][database][session]几个节点
> 
> ```
> ##################### Grafana Configuration Example #####################
> #
> # Everything has defaults so you only need to uncomment things you want to
> # change
> 
> # possible values : production, development
> ;app_mode = production
> 
> # instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
> ;instance_name = ${HOSTNAME}
> 
> #################################### Paths ####################################
> [paths]
> # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
> data = /data/grafana/5.2.1/data
> 
> # Directory where grafana can store logs
> logs = /data/grafana/5.2.1/log
> 
> # Directory where grafana will automatically scan and look for plugins
> plugins = /data/grafana/5.2.1/plugins
> 
> # folder that contains provisioning config files that grafana will apply on startup and while running.
> ;provisioning = conf/provisioning
> 
> #################################### Server ####################################
> [server]
> domain = autohome.com.cn
> # Protocol (http, https, socket)
> protocol = http
> 
> # The ip address to bind to, empty will bind to all interfaces
> ;http_addr =
> 
> # The http port  to use
> ;http_port = 3000
> 
> # The public facing domain name used to access grafana from a browser
> ;domain = localhost
> 
> # Redirect to correct domain if host header does not match domain
> # Prevents DNS rebinding attacks
> ;enforce_domain = false
> 
> # The full public facing url you use in browser, used for redirects and emails
> # If you use reverse proxy and sub path specify full url (with sub path)
> root_url = %(protocol)s://%(domain)s/
> 
> # Log web requests
> ;router_logging = false
> 
> # the path relative working path
> ;static_root_path = public
> 
> # enable gzip
> ;enable_gzip = false
> 
> # https certs & key file
> ;cert_file =
> ;cert_key =
> 
> # Unix socket path
> ;socket =
> 
> #################################### Database ####################################
> [database]
> # You can configure the database connection by specifying type, host, name, user and password
> # as separate properties or as on string using the url properties.
> 
> # Either "mysql", "postgres" or "sqlite3", it's your choice
> type = mysql
> host = xxx.autohome.com.cn:3307
> name = xxx
> user = xxx
> # If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
> password = """xxxxxx"""
> 
> # Use either URL or the previous fields to configure the database
> # Example: mysql://user:secret@host:port/database
> ;url =
> 
> # For "postgres" only, either "disable", "require" or "verify-full"
> ;ssl_mode = disable
> 
> # For "sqlite3" only, path relative to data_path setting
> ;path = grafana.db
> 
> # Max idle conn setting default is 2
> ;max_idle_conn = 2
> 
> # Max conn setting default is 0 (mean not set)
> ;max_open_conn =
> 
> # Connection Max Lifetime default is 14400 (means 14400 seconds or 4 hours)
> ;conn_max_lifetime = 14400
> 
> # Set to true to log the sql calls and execution times.
> log_queries =
> 
> #################################### Session ####################################
> [session]
> # Either "memory", "file", "redis", "mysql", "postgres", default is "file"
> ;provider = file
> 
> # Provider config options
> # memory: not have any config yet
> # file: session dir path, is relative to grafana data_path
> # redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
> # mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
> # postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
> ;provider_config = sessions
> 
> # Session cookie name
> ;cookie_name = grafana_sess
> 
> # If you use session in https only, default is false
> ;cookie_secure = false
> 
> # Session life time, default is 86400
> ;session_life_time = 86400
> 
> provider = mysql
> provider_config = """xxx:xxx@tcp(xxxx.autohome.com.cn:3307)/xxxx"""
> cookie_name = grafana_sess
> cookie_secure = false
> session_life_time = 2592000
> 
> #################################### Data proxy ###########################
> [dataproxy]
> 
> # This enables data proxy logging, default is false
> ;logging = false
> 
> #################################### Analytics ####################################
> [analytics]
> # Server reporting, sends usage counters to stats.grafana.org every 24 hours.
> # No ip addresses are being tracked, only simple counters to track
> # running instances, dashboard and error counts. It is very helpful to us.
> # Change this option to false to disable reporting.
> ;reporting_enabled = true
> 
> # Set to false to disable all checks to https://grafana.net
> # for new vesions (grafana itself and plugins), check is used
> # in some UI views to notify that grafana or plugin update exists
> # This option does not cause any auto updates, nor send any information
> # only a GET request to http://grafana.com to get latest versions
> ;check_for_updates = true
> 
> # Google Analytics universal tracking code, only enabled if you specify an id here
> ;google_analytics_ua_id =
> 
> #################################### Security ####################################
> [security]
> # default admin user, created on startup
> ;admin_user = admin
> 
> # default admin password, can be changed before first start of grafana,  or in profile settings
> ;admin_password = admin
> 
> # used for signing
> ;secret_key = SW2YcwTIb9zpOOhoPsMm
> 
> # Auto-login remember days
> ;login_remember_days = 7
> ;cookie_username = grafana_user
> ;cookie_remember_name = grafana_remember
> 
> # disable gravatar profile images
> ;disable_gravatar = false
> 
> # data source proxy whitelist (ip_or_domain:port separated by spaces)
> ;data_source_proxy_whitelist =
> 
> # disable protection against brute force login attempts
> ;disable_brute_force_login_protection = false
> 
> #################################### Snapshots ###########################
> [snapshots]
> # snapshot sharing options
> ;external_enabled = true
> ;external_snapshot_url = https://snapshots-origin.raintank.io
> ;external_snapshot_name = Publish to snapshot.raintank.io
> 
> # remove expired snapshot
> ;snapshot_remove_expired = true
> 
> #################################### Dashboards History ##################
> [dashboards]
> # Number dashboard versions to keep (per dashboard). Default: 20, Minimum: 1
> ;versions_to_keep = 20
> 
> #################################### Users ###############################
> [users]
> # disable user signup / registration
> allow_sign_up = true
> 
> # Allow non admin users to create organizations
> allow_org_create = true
> 
> # Set to true to automatically assign new users to the default organization (id 1)
> auto_assign_org = true
> 
> # Default role new users will be automatically assigned (if disabled above is set to true)
> auto_assign_org_role = Viewer
> 
> # Background text for the user field on the login page
> login_hint = email or username
> 
> # Default UI theme ("dark" or "light")
> default_theme = dark
> 
> # External user management, these options affect the organization users view
> ;external_manage_link_url =
> ;external_manage_link_name =
> ;external_manage_info =
> 
> # Viewers can edit/inspect dashboard settings in the browser. But not save the dashboard.
> ;viewers_can_edit = false
> 
> [auth]
> # Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
> ;disable_login_form = false
> 
> # Set to true to disable the signout link in the side menu. useful if you use auth.proxy, defaults to false
> ;disable_signout_menu = false
> 
> #################################### Anonymous Auth ##########################
> [auth.anonymous]
> # enable anonymous access
> enabled = true
> 
> # specify organization name that should be used for unauthenticated users
> org_name = Main Org.
> 
> # specify role for unauthenticated users
> org_role = Viewer
> 
> #################################### Github Auth ##########################
> [auth.github]
> ;enabled = false
> ;allow_sign_up = true
> ;client_id = some_id
> ;client_secret = some_secret
> ;scopes = user:email,read:org
> ;auth_url = https://github.com/login/oauth/authorize
> ;token_url = https://github.com/login/oauth/access_token
> ;api_url = https://api.github.com/user
> ;team_ids =
> ;allowed_organizations =
> 
> #################################### Google Auth ##########################
> [auth.google]
> ;enabled = false
> ;allow_sign_up = true
> ;client_id = some_client_id
> ;client_secret = some_client_secret
> ;scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
> ;auth_url = https://accounts.google.com/o/oauth2/auth
> ;token_url = https://accounts.google.com/o/oauth2/token
> ;api_url = https://www.googleapis.com/oauth2/v1/userinfo
> ;allowed_domains =
> 
> #################################### Generic OAuth ##########################
> [auth.generic_oauth]
> ;enabled = false
> ;name = OAuth
> ;allow_sign_up = true
> ;client_id = some_id
> ;client_secret = some_secret
> ;scopes = user:email,read:org
> ;auth_url = https://foo.bar/login/oauth/authorize
> ;token_url = https://foo.bar/login/oauth/access_token
> ;api_url = https://foo.bar/user
> ;team_ids =
> ;allowed_organizations =
> 
> #################################### Grafana.com Auth ####################
> [auth.grafana_com]
> ;enabled = false
> ;allow_sign_up = true
> ;client_id = some_id
> ;client_secret = some_secret
> ;scopes = user:email
> ;allowed_organizations =
> 
> #################################### Auth Proxy ##########################
> [auth.proxy]
> ;enabled = false
> ;header_name = X-WEBAUTH-USER
> ;header_property = username
> ;auto_sign_up = true
> ;ldap_sync_ttl = 60
> ;whitelist = 192.168.1.1, 192.168.2.1
> 
> #################################### Basic Auth ##########################
> [auth.basic]
> ;enabled = true
> 
> #################################### Auth LDAP ##########################
> [auth.ldap]
> ;enabled = false
> ;config_file = /etc/grafana/ldap.toml
> ;allow_sign_up = true
> 
> #################################### SMTP / Emailing ##########################
> [smtp]
> enabled = true
> host = xxxx
> user =xxxx
> # If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
> password =xxxx
> ;cert_file =
> ;key_file =
> ;skip_verify = false
> from_address = xxxx
> from_name = Grafana
> # EHLO identity in SMTP dialog (defaults to instance_name)
> ;ehlo_identity = dashboard.example.com
> 
> [emails]
> ;welcome_email_on_sign_up = false
> 
> #################################### Logging ##########################
> [log]
> # Either "console", "file", "syslog". Default is console and  file
> # Use space to separate multiple modes, e.g. "console file"
> ;mode = console file
> 
> # Either "debug", "info", "warn", "error", "critical", default is "info"
> ;level = info
> 
> # optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
> ;filters =
> 
> # For "console" mode only
> [log.console]
> ;level =
> 
> # log line format, valid options are text, console and json
> ;format = console
> 
> # For "file" mode only
> [log.file]
> ;level =
> 
> # log line format, valid options are text, console and json
> ;format = text
> 
> # This enables automated log rotate(switch of following options), default is true
> ;log_rotate = true
> 
> # Max line number of single file, default is 1000000
> ;max_lines = 1000000
> 
> # Max size shift of single file, default is 28 means 1 << 28, 256MB
> ;max_size_shift = 28
> 
> # Segment log daily, default is true
> ;daily_rotate = true
> 
> # Expired days of log file(delete after max days), default is 7
> ;max_days = 7
> 
> [log.syslog]
> ;level =
> 
> # log line format, valid options are text, console and json
> ;format = text
> 
> # Syslog network type and address. This can be udp, tcp, or unix. If left blank, the default unix endpoints will be used.
> ;network =
> ;address =
> 
> # Syslog facility. user, daemon and local0 through local7 are valid.
> ;facility =
> 
> # Syslog tag. By default, the process' argv[0] is used.
> ;tag =
> 
> #################################### Alerting ############################
> [alerting]
> # Disable alerting engine & UI features
> ;enabled = true
> # Makes it possible to turn off alert rule execution but alerting UI is visible
> ;execute_alerts = true
> 
> #################################### Internal Grafana Metrics ##########################
> # Metrics available at HTTP API Url /metrics
> [metrics]
> # Disable / Enable internal metrics
> ;enabled           = true
> 
> # Publish interval
> ;interval_seconds  = 10
> 
> # Send internal metrics to Graphite
> [metrics.graphite]
> # Enable by setting the address setting (ex localhost:2003)
> ;address =
> ;prefix = prod.grafana.%(instance_name)s.
> 
> #################################### Distributed tracing ############
> [tracing.jaeger]
> # Enable by setting the address sending traces to jaeger (ex localhost:6831)
> ;address = localhost:6831
> # Tag that will always be included in when creating new spans. ex (tag1:value1,tag2:value2)
> ;always_included_tag = tag1:value1
> # Type specifies the type of the sampler: const, probabilistic, rateLimiting, or remote
> ;sampler_type = const
> # jaeger samplerconfig param
> # for "const" sampler, 0 or 1 for always false/true respectively
> # for "probabilistic" sampler, a probability between 0 and 1
> # for "rateLimiting" sampler, the number of spans per second
> # for "remote" sampler, param is the same as for "probabilistic"
> # and indicates the initial sampling rate before the actual one
> # is received from the mothership
> ;sampler_param = 1
> 
> #################################### Grafana.com integration  ##########################
> # Url used to to import dashboards directly from Grafana.com
> [grafana_com]
> ;url = https://grafana.com
> 
> #################################### External image storage ##########################
> [external_image_storage]
> # Used for uploading images to public servers so they can be included in slack/email messages.
> # you can choose between (s3, webdav, gcs, azure_blob, local)
> ;provider =
> 
> [external_image_storage.s3]
> ;bucket =
> ;region =
> ;path =
> ;access_key =
> ;secret_key =
> 
> [external_image_storage.webdav]
> ;url =
> ;public_url =
> ;username =
> ;password =
> 
> [external_image_storage.gcs]
> ;key_file =
> ;bucket =
> ;path =
> 
> [external_image_storage.azure_blob]
> ;account_name =
> ;account_key =
> ;container_name =
> 
> [external_image_storage.local]
> # does not require any configuration
> ```

大佬，我挨个版本一个一个试，终于在7.0版本试成功了，已经有效果了，多谢大佬
![image](https://user-images.githubusercontent.com/22983421/148021162-6ea05b95-3334-4cb0-83f6-bc4fe677ccf7.png)

**Comment by nfw999** [comment]
其他版本还是有问题 ？ 跟https有关系么，试下http?  看下[server]节点下配置

**Comment by uglyliu** [comment]
> 其他版本还是有问题 ？ 跟https有关系么，试下http? 看下[server]节点下配置

试过直接跳过nginx，反问IP:3000也是同样报404，server配置如下，后来用我从5.2.1直接升级到7.0版本就好了
[server]
# Protocol (http, https, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
#domain = dashboard.ixiaochuan.cn
domain = dashboard.ixiaochuan.cn

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://dashboard.ixiaochuan.cn

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =

**Comment by uglyliu** [comment]
> 其他版本还是有问题 ？ 跟https有关系么，试下http? 看下[server]节点下配置

server节点配置如下所示，有试过跳过nginx，使用IP:3000端口访问也是404，后面我把grafana直接从5.2.1升级到7.0版本就好了，grafana.ini还是之前的配置
```
[server]
# Protocol (http, https, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
#domain = dashboard.ixiaochuan.cn
domain = dashboard.ixiaochuan.cn

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://dashboard.ixiaochuan.cn

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =
```
