### ISSUE TITLE
yum源安装的grafana，先安装不了这个插件

### ISSUE THREAD

**Issue by Seven-Wu-F** [AutohomeCorp/autohome-compareQueries-datasource#30]
我把autohome-compareQueries-datasource这个包放在/var/lib/grafana/plugins下
 /etc/grafana/grafana.ini也添加了，
[plugins]
;enable_alpha = true
;app_tls_skip_verify_insecure = true
# Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never load
ed.
;allow_loading_unsigned_plugins = autohome-compareQueries-datasource
# Enable or disable installing plugins directly from within Grafana.
;plugin_admin_enabled = true
;plugin_admin_external_manage_enabled = true
;plugin_catalog_url = https://grafana.com/grafana/plugins/
 
版本Grafana v8.2.2

**Comment by nfw999** [comment]
![image](https://user-images.githubusercontent.com/33611490/148149818-9708675e-dc08-4966-b995-798f404f74f4.png)

去掉allow_loading_unsigned_plugins 前的分号试试

**Comment by nfw999** [comment]
配置值应该与plugin.json中id一致：autohome-comparequeries-datasource，注意大小写

**Comment by Seven-Wu-F** [comment]
> 配置值应该与plugin.json中id一致：autohome-comparequeries-datasource，注意大小写

感谢大佬，已经安装进来了
