### ISSUE TITLE
Grafana v8.4.0-pre (017397a) 版本无法安装 v1.0.1 插件

### ISSUE THREAD

**Issue by luofeng3465** [AutohomeCorp/autohome-compareQueries-datasource#31]
grafana 版本： Grafana v8.4.0-pre (017397a)
将 v1.0.1插件放入到 /var/lib/grafana/plugins 目录重启 grafana 后无法识别，在DataSource 添加栏找不到对应的数据源，麻烦兼容下，谢谢！（在7.5版本测试是正常的）

![image](https://user-images.githubusercontent.com/31304617/148199338-afad816b-1b58-4b38-9622-60032a28daf5.png)

**Comment by IrvingYuanStu** [comment]
> grafana 版本： Grafana v8.4.0-pre (017397a) 将 v1.0.1插件放入到 /var/lib/grafana/plugins 目录重启 grafana 后无法识别，在DataSource 添加栏找不到对应的数据源，麻烦兼容下，谢谢！（在7.5版本测试是正常的）
> 
> ![image](https://user-images.githubusercontent.com/31304617/148199338-afad816b-1b58-4b38-9622-60032a28daf5.png)

grafana.ini配置，allow_loading_unsigned_plugins添加配置

**Comment by luofeng3465** [comment]
> 

allow_loading_unsigned_plugins 中添加了 autohome-compareQueries-datasource 重启后还是无法识别，7.5版本版本能正常识别~

**Comment by luofeng3465** [comment]
> > grafana 版本： Grafana v8.4.0-pre (017397a) 将 v1.0.1插件放入到 /var/lib/grafana/plugins 目录重启 grafana 后无法识别，在DataSource 添加栏找不到对应的数据源，麻烦兼容下，谢谢！（在7.5版本测试是正常的）
> > ![image](https://user-images.githubusercontent.com/31304617/148199338-afad816b-1b58-4b38-9622-60032a28daf5.png)
> 
> grafana.ini配置，allow_loading_unsigned_plugins添加配置

可以了，谢谢

**Comment by leoswing** [comment]
@IrvingYuanStu @luofeng3465  version 2.0.2 is released now, it's compatible with Grafana version 8, 9, 10, and latest 11.

Also it provides signed with public signature, which you don't need any `allow_loading_unsigned_plugins` config setting.

Repo details:  [CompareQueries](https://github.com/leoswing/comparequeries-datasource-rc)

Also you could search on [Grafana plugin website](https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/)
