### ISSUE TITLE
can the plugin select the time-shifted group automatically when I select the normal group

### ISSUE THREAD

**Issue by 15klli** [AutohomeCorp/autohome-compareQueries-datasource#32]
Like this:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/17797189/156737267-32753f9a-cf1a-4ac7-9629-af4fed8c181b.png">
if I select the group "httpCode: 500" , then the group "httpCode: 500_1d" was selected automatically

**Comment by nfw999** [comment]
I'm sorry this feature may not be available.
This plugin is just a datasource plugin，I think the feature is triggered in the panel plugin and need the datasource plugin to provide the necessary data
