### ISSUE TITLE
请问一下支持的grafana版本是多少

### ISSUE THREAD

**Issue by zmwxiaoming** [AutohomeCorp/autohome-compareQueries-datasource#33]
请问一下支持的grafana版本是多少, 我的版本是8.5.9, 按照步骤安装了, 找不到

**Comment by zmwxiaoming** [comment]
找到原因了:
Skipping loading plugin due to problem with signature
修改/grafana-8.5.9/conf/defaults.ini文件如下的配置 app_mode = production 改为:app_mode = development

WARN [08-06|09:58:20] Permitting unsigned plugin. This is not recommended logger=plugin.signature.validator pluginID=autohome-comparequeries-datasource pluginDir=/Users/zhaomingwei/plugins/grafana-8.5.9/data/plugins/autohome-comparequeries-datasource

**Comment by nfw999** [comment]
>=5.xx
