### ISSUE TITLE
autohome-compareQueries-datasource/src/module.js: no such file or directory" 

### ISSUE THREAD

**Issue by rajnishnpst** [AutohomeCorp/autohome-compareQueries-datasource#34]
Hi,
 I have allowed unsigned in defaults.ini but plugin doesn't opens.
Only in loading state, in logs getting below error:

 error="open /opt/grafana/data/plugins/
autohome-compareQueries-datasource/src/module.js: no such file or directory" 
can somebody help ?

**Comment by maxfagotto** [comment]
For me works building the plugin:
yarn install --pure-lockfile
yarn build
copying into the grafana plugins director and restarting it.

**Comment by morreke** [comment]
> yarn install --pure-lockfile
> yarn build
> copying into the grafana plugins director and restarting it.

Solved the problem for me
Thanks

**Comment by nesta219** [comment]
Is there a reason that the `dist/` folder was removed from the repository though?  We didn't used to have to build the plugin ourselves, it was already built and consumable directly.  I'd kindly request that the built files in the `dist/` folder be re-added to the project

**Comment by maxfagotto** [comment]
> Is there a reason that the `dist/` folder was removed from the repository though? We didn't used to have to build the plugin ourselves, it was already built and consumable directly. I'd kindly request that the built files in the `dist/` folder be re-added to the project

+1

**Comment by nfw999** [comment]
the dist/ folder has been re-added to the project
