### ISSUE TITLE
同比环比相关曲线对比的标题日期时间有误

### ISSUE THREAD

**Issue by leoswing** [AutohomeCorp/autohome-compareQueries-datasource#35]
- 背景问题
使用了该插件后，在grafana的同比数据对比后，显示的文本不大对，错误地展示为当天日期了，麻烦帮忙处理一下
![企业微信截图_c77e044d-a426-4899-bcf6-b9c8730f0ab8](https://user-images.githubusercontent.com/17714673/194685489-4c74c1f9-23b4-4fae-8783-73c50659292f.png)

- 期待表现
希望能在对应的同比或者环比的数据文本上，能够展示对应的真实的日期。

**Comment by nfw999** [comment]
这个插件的主要作用就是把同环比的数据和当前数据 显示在同一X轴（时间刻度）的上进行对比，图标上的数据由X轴（时间）和Y轴（数据值）确定定位，数据曲线的名字（xxx_1d）即代表了它是同比1天的数据

你的这个需求更像是一个panel插件需求，数据需要三个维度展示数据，显示时间（数据真实X轴时间）、渲染时间、数据值
