### ISSUE TITLE
undefined: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by nereus-east** [AutohomeCorp/autohome-compareQueries-datasource#37]
![image](https://user-images.githubusercontent.com/61938735/205884841-8b9a5d44-3426-4cf3-a311-89c88b55fba8.png)
Grafana version: 9.2.2

看上去是 grafana的Service没有返回相应的response导致的
API: https://HOSTNAME/api/datasources/proxy/10/_msearch?max_concurrent_shard_requests=256
正常来说这里的responses的count，应该和query的数量一致。但是出现这个error的时候，count 比正常少 1
![image](https://user-images.githubusercontent.com/61938735/205885413-c744b3c2-288b-45a3-ae9c-431aeca6b7cb.png)

**Comment by leoswing** [comment]
@nereus-east Hi ， version 2.0.2 is released , which is compatible with Grafana 10 & 11, also it provides signed with public signature, welcome to use this latest plugin ~ repo details: [compareQueries](https://github.com/leoswing/comparequeries-datasource-rc)
