### ISSUE TITLE
Failed to fetch Instantiating autohome-comparequeries-datasource/module.js in Grafana 10

### ISSUE THREAD

**Issue by leoswing** [AutohomeCorp/autohome-compareQueries-datasource#39]
Fail to fetch autohome-comparequeries-datasource plugin in Grafana 10，The errors is shown as below:

Error: Failed to fetch Instantiating https://xxx.oa.com/grafana-gray/public/plugins/autohome-comparequeries-datasource/module.js Loading plugins/autohome-comparequeries-datasource/module

Could anyone help to solve this? Much appreciated if someone could help!!

**Comment by nfw999** [comment]
1、Check if the plug-in is the latest version
2、Check whether grafana is set to allow loading as a signature plugin
```
[plugins]
……
 allow_loading_unsigned_plugins = autohome-comparequeries-datasource
……

```

If not resolved please provide more context，such as grafana minor version

**Comment by leoswing** [comment]
> 1、Check if the plug-in is the latest version 2、Check whether grafana is set to allow loading as a signature plugin
> 
> ```
> [plugins]
> ……
>  allow_loading_unsigned_plugins = autohome-comparequeries-datasource
> ……
> ```
> 
> If not resolved please provide more context，such as grafana minor version

It's the latest version and allow_loading_unsigned_plugins options has been set in grafana config, error still occurs with error message Failed to fetch...， downgrade grafana to 9.x solves this problem.

**Comment by beramod** [comment]
@leoswing Hello. Do you happen to know if the version 9.4.3 also supports it?
When I check it with grafana-cli, it is confirmed that it is installed, but it is not available in grafana-ui.

**Comment by leoswing** [comment]
> @leoswing Hello. Do you happen to know if the version 9.4.3 also supports it? When I check it with grafana-cli, it is confirmed that it is installed, but it is not available in grafana-ui.

yes, I use the version 9.4.12, and it still works well, seems grafana 10 could not run with it any more. @beramod
