### ISSUE TITLE
Running with grafana 7.0.0

### ISSUE THREAD

**Issue by saba0815** [AutohomeCorp/autohome-compareQueries-datasource#5]
Hi,
can you confirm that the plugin works on the new grafana 7.0.0 release?

Thx + BR,
Sebastian.

**Comment by juris** [comment]
Hi. I've just updated to Grafana 7.0 and can confirm that plugin is working.

However, there was an issue related to plugin ID change, most likely related to [this commit](https://github.com/AutohomeCorp/autohome-compareQueries-datasource/commit/6482b51f4e24b6701e19218482bb23246d88aaaf)

All the panels were broken till I went to MySQL and adjusted existing datasource:
```
SELECT id FROM grafana.data_source WHERE type = "grafana-Comparequeries-datasource";
+----+
| id |
+----+
|  9 |
+----+
UPDATE grafana.data_source SET type = "autohome-comparequeries-datasource" WHERE id=9;
```

**Comment by saba0815** [comment]
Ok thank you @juris 

What i want to do is display multiple timeshifts of a query in one figure as multiple lines but all i get is the last one (1w)
![Bildschirmfoto 2020-05-25 um 10 24 50](https://user-images.githubusercontent.com/5336085/82794123-43d95b80-9e72-11ea-99c8-216295a4e9ce.png)

Any hints?

Thx + BR,
Sebastian.

**Comment by juris** [comment]
This is how it looks for me with InfluxDB datasource:
![Screenshot 2020-05-25 at 13 09 25](https://user-images.githubusercontent.com/1359141/82803755-c02b6900-9e89-11ea-9e23-09faf13bb5b0.png)

Btw, I'm using this plugin because Influx does not provide timeShift function, but in your case, you could try [native timeShift()](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.timeShift)

**Comment by nfw999** [comment]
Did you update the plugin to the latest version?
Confirm whether it is the same problem as https://github.com/AutohomeCorp/autohome-compareQueries-datasource/issues/2

**Comment by nfw999** [comment]
Did you update the plugin to the latest version?
Confirm whether it is the same problem as https://github.com/AutohomeCorp/autohome-compareQueries-datasource/issues/2

**Comment by saba0815** [comment]
> 
> Btw, I'm using this plugin because Influx does not provide timeShift function, but in your case, you could try [native timeShift()](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.timeShift)

Thank you very much. That is indeed the function that solved it for me.

Maybe the plugin doesn't play well with graphite as TSDB?

Much love,
Sebastian.
