### ISSUE TITLE
Install on Build from source version

### ISSUE THREAD

**Issue by GuilhermeDaniluski** [AutohomeCorp/autohome-compareQueries-datasource#6]
Hello, 
       Thank you for this amazing work.
       I am sorry if this is a noob question, but could you tell me how do i install this plugin in a build from source version of grafana?

Thank You.

**Comment by juris** [comment]
Hi @GuilhermeDaniluski, README.md says
> Clone this project into the grafana plugins directory

So if you've built Grafana in /usr/src/grafana, try to clone the project into /usr/src/grafana/plugins
