### ISSUE TITLE
Grafana 7.1.0 "Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by szerwi** [AutohomeCorp/autohome-compareQueries-datasource#8]
After updating Grafana to version 7.1.0, the plugin stopped working.
![image](https://user-images.githubusercontent.com/19311511/87849682-a38c3a00-c8ea-11ea-8c8e-114d47fc4f40.png)
![image](https://user-images.githubusercontent.com/19311511/87849701-cd456100-c8ea-11ea-82f9-6bd1b004a44b.png)

**Comment by rletocart** [comment]
exact same problem for me, since "apt-get dist-upgrade" on debian buster

**Comment by t413** [comment]
Same here on Grafana v7.1.0 (8101355285) + InfluxDB 1.8.1 + Ubuntu 16.04.6 LTS + armv7l. Query inspector responds with the un-timeshifted data _but won't chart it_, no sign of timeshifted data.

**Comment by juris** [comment]
Same here. Grafana 7.1.2, Influxdb 1.8.1

**Comment by szerwi** [comment]
@nfw999 is there any chance to fix this issue?

**Comment by vshaev** [comment]
Grafana 7.1.3. The plugin is detected but there is no option to select it in the dashboard.

**Comment by szerwi** [comment]
@nfw999 I've updated to the latest library version and on Grafana 7.1.2 I get following error:
` CompareQueries plugin failed
Error: Unexpected token '<' Evaluating https://xxx.xxx.xxx.xxx/public/plugins/autohome-comparequeries-datasource/module.js Loading plugins/autohome-comparequeries-datasource/module`

**Comment by nfw999** [comment]
Sorry for my mistake, now you try again

**Comment by szerwi** [comment]
It's working now. Thanks for the fix :)
