### ISSUE TITLE
Prometheus datasource legend title issue

### ISSUE THREAD

**Issue by dvanderfaeillie** [AutohomeCorp/autohome-compareQueries-datasource#9]
I was having an issue with the following line. Even when inputting a suffix alias nothing was added to the title of my time series.

I solved it by changing 
https://github.com/AutohomeCorp/autohome-compareQueries-datasource/blob/d03bb808f97de59bc20aaa54febb89f3ba97003d/dist/datasource.js#L138

to  `line.title = line.title + '_' + timeShiftAlias `

I also changed this in the line above: `line.title = line.title + '_' + timeShiftValue`

I didn't create a pull request since I'm not entirely sure about this...

**Comment by nfw999** [comment]
Prometheus does have this problem, thank you for your suggestion
